apiVersion: v1
kind: Service
metadata:
  name: testworkflow
  namespace: namespace-workflow-1747807333025
  labels:
    app.kubernetes.io/name: testworkflow
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: testworkflow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000