apiVersion: v1
kind: Service
metadata:
  name: test11
  namespace: namespace-workflow-1747821839536
  labels:
    app.kubernetes.io/name: test11
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: test11
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080